Store last active PHP version and support short switch operator

diff --git a/scripts/switch_php b/scripts/switch_php
--- a/scripts/switch_php
+++ b/scripts/switch_php
@@ -6,17 +6,44 @@ RED="\033[0;31m"
 CYAN="\033[1;36m"
 NC="\033[0m"
 
-readonly phpVersion="$1"
+phpVersion="$1"
+lastVersionFile="$HOME/.cache/switch-php/LAST_VERSION"
+
+# Fail if PHP version is not specified
+if [ -z "$phpVersion" ]; then
+  echo "${RED}No PHP version specified.${NC}"
+  echo "Usage:"
+  echo "  ${CYAN}$0 <php-version>${NC}"
+  exit 1
+fi
+
+# Try to switch back to last active PHP version, if requested and available
+if [ "$phpVersion" = "-" ]; then
+  if [ ! -f "$lastVersionFile" ]; then
+    echo "${RED}No last active PHP version detected; please specify a concrete version instead.${NC}"
+    echo "Usage:"
+    echo "  ${CYAN}$0 <php-version>${NC}"
+    exit 1
+  fi
+
+  phpVersion="$(cat "$lastVersionFile")"
+fi
+
 readonly phpPackage="php@${phpVersion}"
 readonly pcovPackage="pcov@${phpVersion}"
 readonly xdebugPackage="xdebug@${phpVersion}"
 
-if [ -z "$phpVersion" ]; then
-    echo "${RED}No PHP version specified.${NC}"
-    echo "Usage:"
-    echo "  ${CYAN}$0 <php-version>${NC}"
-    exit 1
-fi
+_populate_current_version() {
+  currentVersion="$(php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;' 2>/dev/null || true)"
+
+  if [ ! -f "$lastVersionFile" ]; then
+    mkdir -p "$(dirname "$lastVersionFile")"
+  fi
+
+  if [ -n "$currentVersion" ]; then
+    echo "$currentVersion" > "$lastVersionFile"
+  fi
+}
 
 _activate() {
   brew unlink --quiet php "$phpPackage"
@@ -47,6 +74,8 @@ _write_config() {
   # Disable xdebug by default
   mv "${configDir}/20-xdebug.ini" "${configDir}/20-xdebug.ini.disabled" >/dev/null 2>&1 || true
 }
+
+_populate_current_version
 
 if ls "$(brew --cellar)/${phpPackage}" >/dev/null 2>&1 || brew --prefix --installed "$phpPackage" >/dev/null 2>&1; then
   _activate
